hack/verify_boilerplate: add new generated go markers
kubernetes/repo-infra pull request #215
Opened 2020-12-15 17:46 UTC by cpanato

hack/verify_boilerplate: add new generated go markers

2020-12-15 17:52 UTC, cpanato commented
/assign @justaugustus @BenTheElder

2020-12-15 18:11 UTC, justaugustus requested changes
@cpanato -- Can you alpha-sort the list?

2020-12-16 01:26 UTC, fejta approved these changes

2020-12-16 01:27 UTC, fejta commented
/hold

2020-12-16 08:48 UTC, justaugustus commented
/lgtm
/approve
/hold cancel

2020-12-16 08:50 UTC, merged